version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  nginx: # Name of the 1st service.
    image: nginx
    container_name: api-gateway
    ports:
     - "80:80"
    volumes:
     - ./api_gateway/default.conf:/etc/nginx/conf.d/default.conf
     - ./api_gateway/resolv.conf:/etc/resolv.conf
    depends_on:
     - m-service-1
     - m-service-2
  m-service-1: # Name of the 2nd service.
    container_name: m-service-1
    build: 
      context: ./m-service-1
      dockerfile: Dockerfile.dev
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./m-service-1:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "8081:3000"
      - "9229:9229"
    # tty:
    #   true
    command: sh -c 'npm run debug'
    
  m-service-2: # Name of the 3rd service
    container_name: m-service-2
    build: "./m-service-2"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./m-service-2/src:/usr/src/app/src
    ports:
      - "8082:8002"
    command: bash -c "npm start"